azs:
- cloud_properties:
    zone: us-east1-b
  name: z1
- cloud_properties:
    zone: us-east1-c
  name: z2
- cloud_properties:
    zone: us-east1-d
  name: z3
compilation:
  az: z1
  network: private
  reuse_compilation_vms: true
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: n1-highcpu-8
  workers: 1
disk_types:
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 1024
  name: default
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 1024
  name: 1GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 5120
  name: 5GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 10240
  name: 10GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 51200
  name: 50GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 102400
  name: 100GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 512000
  name: 500GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 1048576
  name: 1TB
networks:
- name: private
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-winnipeg-2019-03-07t19-08z-network
      subnetwork_name: bbl-env-winnipeg-2019-03-07t19-08z-subnet
      tags:
      - bbl-env-winnipeg-2019-03-07t19-08z-internal
    gateway: 10.0.0.1
    range: 10.0.0.0/16
    reserved:
    - 10.0.0.1-10.0.0.255
    static:
    - 10.0.255.0-10.0.255.254
  type: manual
- name: default
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-winnipeg-2019-03-07t19-08z-network
      subnetwork_name: bbl-env-winnipeg-2019-03-07t19-08z-subnet
      tags:
      - bbl-env-winnipeg-2019-03-07t19-08z-internal
    gateway: 10.0.0.1
    range: 10.0.0.0/16
    reserved:
    - 10.0.0.1-10.0.0.255
    static:
    - 10.0.255.0-10.0.255.254
  type: manual
vm_extensions:
- cloud_properties:
    root_disk_size_gb: 1
    root_disk_type: pd-ssd
  name: 1GB_ephemeral_disk
- cloud_properties:
    root_disk_size_gb: 5
    root_disk_type: pd-ssd
  name: 5GB_ephemeral_disk
- cloud_properties:
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: 10GB_ephemeral_disk
- cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
  name: 50GB_ephemeral_disk
- cloud_properties:
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
  name: 100GB_ephemeral_disk
- cloud_properties:
    root_disk_size_gb: 500
    root_disk_type: pd-ssd
  name: 500GB_ephemeral_disk
- cloud_properties:
    root_disk_size_gb: 1000
    root_disk_type: pd-ssd
  name: 1TB_ephemeral_disk
- cloud_properties:
    ephemeral_external_ip: true
  name: internet-required
- cloud_properties:
    ephemeral_external_ip: false
  name: internet-not-required
- cloud_properties:
    preemptible: true
  name: preemptible
- cloud_properties:
    target_pool: bbl-env-winnipeg-2019-03-07t19-08z-concourse
  name: lb
vm_types:
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: default
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: minimal
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: sharedcpu
- cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: small
- cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: small-highmem
- cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: medium
- cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: large
- cloud_properties:
    machine_type: n1-standard-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: extra-large
- cloud_properties:
    machine_type: n1-highcpu-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: small-highcpu
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-1
- cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-2
- cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-4
- cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-8
- cloud_properties:
    machine_type: n1-standard-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-16
- cloud_properties:
    machine_type: n1-standard-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-32
- cloud_properties:
    machine_type: n1-highmem-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-2
- cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-4
- cloud_properties:
    machine_type: n1-highmem-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-8
- cloud_properties:
    machine_type: n1-highmem-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-16
- cloud_properties:
    machine_type: n1-highmem-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-32
- cloud_properties:
    machine_type: n1-highcpu-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-2
- cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-4
- cloud_properties:
    machine_type: n1-highcpu-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-8
- cloud_properties:
    machine_type: n1-highcpu-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-16
- cloud_properties:
    machine_type: n1-highcpu-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-32
- cloud_properties:
    machine_type: f1-micro
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: f1-micro
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: g1-small
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: m3.medium
- cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: m3.large
- cloud_properties:
    machine_type: n1-highcpu-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: c3.large
- cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: r3.xlarge
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: t2.small
