platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: pack-repo
  - name: pipeline-repo
  - name: packs-samples-image
  - name: packs-build-image
  - name: packs-run-image
  - name: lifecycle-image-version

run:
  path: pipeline-repo/tasks/run-acceptance/run
