platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: lifecycle-repo
  - name: pipeline-repo

outputs:
  - name: built-lifecycle-images

run:
  path: pipeline-repo/tasks/lifecycle-build/run
